# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder_tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='previous_folder',
        ),
        migrations.AddField(
            model_name='trash',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folder_tree.TreeFolder'),
        ),
        migrations.AlterField(
            model_name='generalfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generalfile',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='treefolder',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='treefolder',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
