# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_tree', '0002_auto_20161201_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
